### ISSUE TITLE
Missing Lib. logging.h

### ISSUE THREAD

**Issue by silentrob** [schwa-lab/zpar#1]
It is exciting to see this project on Github, however she does not compile.

./src/include/definitions.h:47:30: fatal error: schwa/io/logging.h: No such file or directory
 #include <schwa/io/logging.h>

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-apple-darwin14.0.0/4.9.2/lto-wrapper
Target: x86_64-apple-darwin14.0.0
Configured with: ../gcc-4.9-20141029/configure --enable-languages=c++,fortran
Thread model: posix
gcc version 4.9.2 20141029 (prerelease) (GCC)

**Comment by timdawborn** [comment]
Hi @silentrob,

This is [Schwa Lab](http://schwa.org/)'s fork of ZPar, which is why it depends on [libschwa](https://github.com/schwa-lab/libschwa) being installed. The regular version of ZPar is still [on SourceForce](http://sourceforge.net/projects/zpar/) unfortunately, which is what I imagine you're after.

**Comment by silentrob** [comment]
Wow, that was a fast reply. You are right, I was just hoping this fork as a little more active and developed in the open. Im actually having an issue compiling the main codebase as well. But I suspect that has to do with my version of gcc / os.

**Comment by silentrob** [comment]
Compile issues resolved!
I'm curious to know if you have successfully trained the CCG parser. I see there is no pre-trained english model for it, and Im getting segfaults when using the generic.conparser binary.

**Comment by timdawborn** [comment]
IIRC, we were only playing with the dependency parser, not the CCG parser. @dominickng or @glenpink : did either of you try the CCG parser?

**Comment by dominickng** [comment]
I haven't tried the CCG parser, but I think the target and binary is `generic.ccgparser`, not `generic.conparser`. @silentrob, are you following the instructions at http://people.sutd.edu.sg/~yue_zhang/doc/doc/ccg.html?

**Comment by silentrob** [comment]
Crazy, I have noticed some inconsistencies in the docs specifically around what the order of some of the arguments should be, here for example shows the conparser and NOT the ccgparser. https://github.com/schwa-lab/zpar/blob/master/doc/doc/ccg_files/test.sh#L9

```
../../../dist/generic.ccgparser/train train.txt -urules.unary -brules.binary -ctrain.input testdb 1
Training started.
Training iteration is started... 
Loading scores... empty.
Segmentation fault: 11
```

The result unfortunately is the same for that binary as well.

**Comment by silentrob** [comment]
FWIW I'm getting the same results on both 6 and 7, and had hoped maybe something had regressed, but that is not the case.
